cart/urls.py
from django.urls import path, reverse_lazy
from .views import view_cart, add_to_cart, adjust_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    path('', view_cart, name='cart'),
    path('add/<id>/', add_to_cart, name='add'),
    path('adjust/<id>/', adjust_cart, name='adjust_cart'),
    path('remove/<id>/', remove_from_cart, name='remove'),
]

django_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/',TemplateView.as_view(template_name='about.html', extra_context={'title': 'About'}), name='about'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
]

tickets/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'tickets'

urlpatterns = [
    path('bugs/', views.BugListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Bugs'}), name='bugs'),
    path('features/', views.FeaturesListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Features'}), name='features'),
    path('detail/<int:pk>/', views.TicketDetailView.as_view(extra_context={'title': 'Detail'}), name='detail'),
    path('new/', views.TicketCreateView.as_view(extra_context={'title': 'New'}), name='new_ticket'),
    path('detail/<int:pk>/update', views.TicketUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/delete', views.TicketDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/comment', views.add_comment_to_ticket, name='add_comment_to_ticket'),
    path('user-bugs/<username>/', views.UserBugListView.as_view(template_name='tickets/user_tickets.html'), name='user_bugs'),
    path('user-features/<username>/', views.UserFeatureListView.as_view(template_name='tickets/user_tickets.html'), name='user_features'),
    path('vote/<int:pk>/', views.ticket_upvote, name='vote'),
]

tickets/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Ticket(models.Model):
    STATUS = (
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
        ('Pending', 'Pending')
    )

    ISSUE = (
        ('Bug', 'Bug'),
        ('Feature', 'Feature')
    )

    title = models.CharField(max_length=75)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS,default='Pending')
    issue = models.CharField(max_length=20, choices=ISSUE, default='Bug')
    upvotes = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)

        
    def __str__(self):
        return self.title

    
    def get_absolute_url(self):
        return reverse('tickets:detail', kwargs={'pk': self.pk})



class Comments(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, null=True, related_name='comments')
    username = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    comment = models.TextField(null=False, blank=False)
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Comments'


    def __str__(self):
        return f'{self.ticket}: {self.username}'


    def get_absolute_url(self):
        return reverse("ticket:detail")


class Upvoted(models.Model):
    ticket = models.ForeignKey(Ticket, default=None, on_delete=models.CASCADE)
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.user}: {self.ticket}'


    class Meta:
        verbose_name_plural = 'Upvoted'

tickets/forms.py
from django import forms
from .models import Comments


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('comment',)

tickets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from django.contrib import messages
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    FormView)
from .models import Ticket, Upvoted, Comments
from .forms import CommentForm

class BugListView(ListView):
    paginate_by = 5
    model = Ticket

    def get_queryset(self, *args, **kwargs):
        return Ticket.objects.filter(issue='Bug').order_by('-date_posted')
        
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['type'] = 'Bugs'
        is_paginated = True
        return context


class UserBugListView(ListView):
    paginate_by = 5
    model = Ticket

    def get_queryset(self, *args, **kwargs):
        username = get_object_or_404(User, username=self.kwargs.get('username'))
        return Ticket.objects.filter(issue='Bug', username=username).order_by('-date_posted')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['type'] = 'Bugs'
        is_paginated = True
        return context


class FeaturesListView(ListView):
    paginate_by = 5
    model = Ticket

    def get_queryset(self, *args, **kwargs):
        return Ticket.objects.filter(issue='Feature').order_by('-date_posted')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['type'] = 'Features'
        is_paginated = True
        return context


class UserFeatureListView(ListView):
    paginate_by = 5
    model = Ticket

    def get_queryset(self, *args, **kwargs):
        username = get_object_or_404(User, username=self.kwargs.get('username'))
        return Ticket.objects.filter(issue='Feature', username=username).order_by('-date_posted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'Features'
        is_paginated = True
        return context


class TicketDetailView(DetailView):
    model = Ticket

    def get_object(self, queryset=None):
        ticket = super().get_object()
        ticket.views += 1
        ticket.save()
        return ticket
    

class TicketCreateView(LoginRequiredMixin ,CreateView):
    model = Ticket
    fields = ['title', 'issue', 'description',]

    def form_valid(self, form):
        form.instance.username = self.request.user
        return super().form_valid(form)


class TicketUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Ticket
    fields = ['title', 'description']

    def form_valid(self, form):
        form.instance.username = self.request.user

        return super().form_valid(form)

    def test_func(self):
        ticket = self.get_object()
        if self.request.user == ticket.username:
            return True
        return False


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ticket
    success_url = '/'

    def test_func(self):
        ticket = self.get_object()
        if self.request.user == ticket.username:
            return True
        return False


@login_required
def add_comment_to_ticket(request, pk):
    ticket = get_object_or_404(Ticket, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.ticket = ticket
            print(request.user)
            comment.username = request.user
            comment.save()
            return redirect('tickets:detail', pk=ticket.pk)
    else:
        form = CommentForm()  
    return render(request, 'tickets/comment_form.html', {'form': form, 'title': ticket.title, 'issue':ticket.issue})


@login_required
def ticket_upvote(request, pk=None):
    
    ticket = get_object_or_404(Ticket, pk=pk)
    try:
        user = User.objects.get(username=request.user)
    except BaseException:
        user = None

    if user:
        try:
            upvoted = Upvoted.objects.get(ticket=ticket, user=request.user)
            print(upvoted)
        except ObjectDoesNotExist:
            ticket_voted = Ticket.objects.get(pk=pk)
            ticket_voted.upvotes = F('upvotes') + 1
            upvote = Upvoted()
            upvote.user = request.user
            upvote.ticket = ticket
            ticket_voted.save()
            upvote.save()
            messages.success(request, 'Your vote has been recorded. Thanks for supporting this ticket.')
        else:
            messages.warning(request, 'You have already voted on this item.')

    return redirect('tickets:detail', ticket.pk) 

tickets/templates/tickets/bugs.html
{% extends 'base.html' %}

{% block content %}
<div class="col-12 col-md-10 col-lg-8 mx-auto mt-5">
    {% for bug in bugs %}
        <div class="col-12">
            <div class="border border-info rounded-sm">
                <h2>{{ bug.title }}</h2>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

tickets/templates/tickets/comment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 col-sm-10 col-md-8 col-lg-6 mx-auto mt-3 mb-5 pt-5">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add new comment for {{ issue|lower }}: {{ title }}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-primary">Save</button>
        </div>
    </form>
</div>

{% endblock %}

tickets/templates/tickets/ticket_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group mt-2">
            <legend class="border-bottom mb-5">Delete Request</legend>
            <p>You are about to delete the request: <strong>{{ object.title }}</strong>. Do you wish to continue?</p>
        </fieldset>
        <div class="form-group mt-3">
            <a class="btn btn-outline-info mr-2" href="{% url 'tickets:detail' object.id %}">Cancel</a>
            <button class="btn btn-danger ml-2" type="submit">Delete</button>
        </div>
    </form>
</div>

{% endblock %}

tickets/templates/tickets/ticket_detail.html
{% extends 'base.html' %}

{% block content %}
    <!-- Ticket Details -->
    <div class="col-12 col-lg-8 mx-auto mt-5 pt-1 mb-2">
        <article class="border border-color-faded rounded-sm my-3 box-shadow bg-gray-light">
            <div class="px-3">
                <div class="d-flex justify-content-between my-1">
                    <div class="d-flex flex-grow-1 flex-shrink-1 ">
                        <h2><span
                                class="badge badge-secondary badge-ticket badge-ticket-{{ ticket.status|lower|cut:' ' }}">{{ object.status }}
                            </span>
                            <span class="text-decoration-none header-normal">{{ object.title }}</span></h2>
                    </div>
                    <div class="d-flex align-self-start ml-3 my-1">
                        <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="far fa-thumbs-up"></i>  {{ object.upvotes }}</div>
                        <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="fas fa-binoculars"></i>  {{ object.views }}</div>
                        <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="far fa-comment-alt"></i>  {{ object.comments.count }}</div>
                    </div>
                </div>
            </div>
            <div class="pb-1">
                <div class="px-3">
                    <div class="d-flex justify-content-between py-1 px-1">
                        <div class="d-flex flex-grow-1 flex-shrink-1">
                            {% if type == 'Bugs' %}
                            <a class="mr-2 text-decoration-none"
                                href="{% url 'tickets:user_bugs' ticket.username.username %}"><small>by: {{ object.username }}</small></a>
                            {% elif type == 'Features' %}
                            <a class="mr-2 text-decoration-none"
                                href="{% url 'tickets:user_features' ticket.username.username %}"><small>by: {{ object.username }}</small></a>
                            {% endif %}
                        </div>
                        <div class="d-flex align-self-start">
                            <small class="text-muted">{{ object.date_posted|date:"d F, Y" }}</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="border-bottom border-top bg-white">
                <div class="p-3">
                    <div class="">{{ object.description|safe|linebreaks }}</div>
                </div>
            </div>
            <!-- Control Buttons -->
            <div class="bg-white d-flex flex-row justify-content-between">
                <div class="my-3 mx-3 justify-content-start">
                    {% if user.is_authenticated %}
                        <a class="btn btn-outline-primary mx-1" href="{% url 'tickets:add_comment_to_ticket' pk=object.id %}">Comment</a>
                    {% endif %}
                </div>
                <div class="m-3 justify-content-end">
                    {% if object.username == user %}
                        <a class="btn btn-outline-secondary mx-1" href="{% url 'tickets:update' object.id %}">Update</a>
                        <a class="btn btn-outline-danger" href="{% url 'tickets:delete' object.id %}">Delete</a>
                    {% else %}
                        {% if object.issue == 'Bug' %}
                            <a class="btn btn-outline-success mx-1" href="{% url 'tickets:vote' pk=object.id %}">Vote</a>
                        {% else %}
                            <a class="btn btn-success mx-1" href="{% url 'cart:add' id=object.id %}">Add to Cart</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </article>
    </div>
    <!-- End of Ticket Details -->
    <!-- Comments -->
    <div class="col-12 col-lg-8 mx-auto mt-3 mb-5 pb-5">
        {% for comment in object.comments.all %}
            <article class="border border-color-faded rounded-sm my-3 box-shadow bg-gray-light">
                <div class="px-3 py-2">
                    <div class="d-flex justify-content-between my-1">
                        <div class="d-flex flex-grow-1 flex-shrink-1 ">
                            <div class="d-flex flex-grow-1 flex-shrink-1">
                                <div class="mr-2"><span class="text-secondary"><i class="far fa-comment-alt"></i></span> {{ comment.username }}</div>
                            </div>
                            <div class="d-flex justify-content-end">
                                <small class="text-muted">{{ comment.date_created|date:"d F, Y" }}</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="border-bottom border-top bg-white">
                    <div class="p-3">
                        <p class="text-dark">{{ comment.comment|safe|linebreaks }}</p>
                    </div>
                </div>
            </article>
        {% empty %}
            <p>No comments posted.</p>
        {% endfor %}
    </div>
    <!-- End of Comments -->
{% endblock %}

tickets/templates/tickets/ticket_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 col-lg-8 mx-auto mt-5 pt-2">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Ticket Request</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

tickets/templates/tickets/tickets.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12 col-lg-8 mx-auto mt-5 pt-1 mb-5 pb-5">
        {% if type == 'Bugs' %}
            <h3><i class="fas fa-spider"></i> {{ type }}</h3>
        {% else %}
            <h3><i class="fas fa-tag"></i> {{ type }}</h3>
        {% endif %}
        <!-- Tickets list -->
        {% for ticket in object_list %}
            <article class="border border-color-faded rounded-sm my-3 box-shadow bg-gray-light">
                <div class="px-3">
                    <div class="d-flex justify-content-between my-1">
                        <div class="d-flex flex-grow-1 flex-shrink-1 ">
                            <h2><span
                                    class="badge badge-secondary badge-ticket badge-ticket-{{ ticket.status|lower|cut:' ' }}">{{ ticket.status }}
                                </span>
                                <a class="text-decoration-none header-normal"
                                    href="{% url 'tickets:detail' ticket.id %}">{{ ticket.title }}</a></h2>
                        </div>
                        <div class="d-flex align-self-start ml-3 my-1">
                            <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="far fa-thumbs-up"></i>  {{ ticket.upvotes }}</div>
                            <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="fas fa-binoculars"></i>  {{ ticket.views }}</div>
                            <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="far fa-comment-alt"></i>  {{ ticket.comments.count }}</div>
                        </div>
                    </div>
                </div>
                <div class="pb-1">
                    <div class="px-3">
                        <div class="d-flex justify-content-between py-1 px-1">
                            <div class="d-flex flex-grow-1 flex-shrink-1">
                                {% if type == 'Bugs' %}
                                <a class="mr-2 text-decoration-none"
                                    href="{% url 'tickets:user_bugs' ticket.username.username %}"><small>by: {{ ticket.username }}</small></a>
                                {% elif type == 'Features' %}
                                <a class="mr-2 text-decoration-none"
                                    href="{% url 'tickets:user_features' ticket.username.username %}"><small>by: {{ ticket.username }}</small></a>
                                {% endif %}
                            </div>
                            <div class="d-flex align-self-start">
                                <small class="text-muted">{{ ticket.date_posted|date:"d F, Y" }}</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="border-bottom border-top bg-white">
                    <div class="p-3">
                        <div class="">{{ ticket.description|linebreaks|truncatechars_html:200 }}</div>
                    </div>
                </div>
            </article>
        {% endfor %}
        <!-- End of Tickets List -->
        
        <!-- Pagination -->
        {% if is_paginated %}
            <div class="mt-4 pt-3">
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-secondary btn-sm" href="?page=1">First</a>
                    <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                        <a class="btn btn-secondary btn-sm" href="?page={{ page }}">{{ page }}</a>
                    {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                            <a class="btn btn-outline-secondary btn-sm" href="?page={{ page }}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            </div>
        {% endif%}
        <!-- End of Pagination -->
    </div>
{% endblock %}

tickets/templates/tickets/user_bugs.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12 col-sm-10 col-lg-8 mx-auto mt-3">
        <h1 class="mb-5">Bugs by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
        {% for bug in bugs %}
            <article class="border border-secondary rounded-lg pl-2 content-area">
                <div class="">
                    <div class="pb-1 mb-3 border-bottom border-success">
                        <a class="mr-2" href="{% url 'tickets:user' bug.username.username %}">{{ bug.username }}</a>
                        <small class="text-muted">{{ bug.date_posted|date:"d F, Y" }}</small>
                    </div>
                    <h2><a class="" href="{% url 'tickets:detail' bug.id %}">{{ bug.title }}</a></h2>
                    <p class="">{{ bug.description|linebreaks|truncatechars_html:200 }}</p>
                </div>
            </article>
        {% endfor %}
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-secondary btn-sm" href="?page=1">First</a>
                <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
                {% if page_obj.number == page %}
                    <a class="btn btn-secondary btn-sm" href="?page={{ page }}">{{ page }}</a>
                {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-secondary btn-sm" href="?page={{ page }}">{{ page }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif%}
    </div>
{% endblock %}

tickets/templates/tickets/user_tickets.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12 col-lg-8 mx-auto mt-5 pt-1 mb-5 pb-5">
        <h3 class="mb-5">{{ type }} by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
        <!-- Tickets list -->
        {% for ticket in object_list %}
            <article class="border border-color-faded rounded-sm my-3 box-shadow bg-gray-light">
                <div class="px-3">
                    <div class="d-flex justify-content-between my-1">
                        <div class="d-flex flex-grow-1 flex-shrink-1 ">
                            <h2><span
                                    class="badge badge-secondary badge-ticket badge-ticket-{{ ticket.status|lower|cut:' ' }}">{{ ticket.status }}
                                </span>
                                <a class="text-decoration-none header-normal"
                                    href="{% url 'tickets:detail' ticket.id %}">{{ ticket.title }}</a></h2>
                        </div>
                        <div class="d-flex align-self-start ml-3 my-1">
                            <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="far fa-thumbs-up"></i>  {{ ticket.upvotes }}</div>
                            <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="fas fa-binoculars"></i>  {{ ticket.views }}</div>
                            <div class="border border-color-faded rounded-sm py-1 px-2 ml-2 badge-ticket"><i class="far fa-comment-alt"></i>  {{ ticket.comments.count }}</div>
                        </div>
                    </div>
                </div>
                <div class="pb-1">
                    <div class="px-3">
                        <div class="d-flex justify-content-between py-1 px-1">
                            <div class="d-flex flex-grow-1 flex-shrink-1">
                                {% if type == 'Bugs' %}
                                <a class="mr-2 text-decoration-none"
                                    href="{% url 'tickets:user_bugs' ticket.username.username %}"><small>by: {{ ticket.username }}</small></a>
                                {% elif type == 'Features' %}
                                <a class="mr-2 text-decoration-none"
                                    href="{% url 'tickets:user_features' ticket.username.username %}"><small>by: {{ ticket.username }}</small></a>
                                {% endif %}
                            </div>
                            <div class="d-flex align-self-start">
                                <small class="text-muted">{{ ticket.date_posted|date:"d F, Y" }}</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="border-bottom border-top bg-white">
                    <div class="p-3">
                        <div class="">{{ ticket.description|linebreaks|truncatechars_html:200 }}</div>
                    </div>
                </div>
            </article>
        {% endfor %}
        <!-- End of Tickets List -->
        
        <!-- Pagination -->
        {% if is_paginated %}
            <div class="mt-4 pt-3">
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-secondary btn-sm" href="?page=1">First</a>
                    <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                        <a class="btn btn-secondary btn-sm" href="?page={{ page }}">{{ page }}</a>
                    {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                            <a class="btn btn-outline-secondary btn-sm" href="?page={{ page }}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-secondary btn-sm" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            </div>
        {% endif%}
        <!-- End of Pagination -->
    </div>
{% endblock %}