cart/urls.py
from django.urls import path, reverse_lazy
from .views import view_cart, add_to_cart, adjust_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    path('', view_cart, name='cart'),
    path('add/<id>/', add_to_cart, name='add'),
    path('adjust/<id>/', adjust_cart, name='adjust_cart'),
    path('remove/<id>/', remove_from_cart, name='remove'),
]

checkout/urls.py
from django.urls import path, reverse_lazy
from .views import checkout

app_name = 'checkout'

urlpatterns = [
    path('', checkout, name='checkout'),
]

django_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/',TemplateView.as_view(template_name='about.html', extra_context={'title': 'About'}), name='about'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
]

tickets/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'tickets'

urlpatterns = [
    path('bugs/', views.BugListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Bugs'}), name='bugs'),
    path('features/', views.FeaturesListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Features'}), name='features'),
    path('detail/<int:pk>/', views.TicketDetailView.as_view(extra_context={'title': 'Detail'}), name='detail'),
    path('new/', views.TicketCreateView.as_view(extra_context={'title': 'New'}), name='new_ticket'),
    path('detail/<int:pk>/update', views.TicketUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/delete', views.TicketDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/comment', views.add_comment_to_ticket, name='add_comment_to_ticket'),
    path('user-bugs/<username>/', views.UserBugListView.as_view(template_name='tickets/user_tickets.html'), name='user_bugs'),
    path('user-features/<username>/', views.UserFeatureListView.as_view(template_name='tickets/user_tickets.html'), name='user_features'),
    path('vote/<int:pk>/', views.ticket_upvote, name='vote'),
]

cart/models.py
from django.db import models

cart/forms.py
from django import forms
from .models import Donate
import datetime

class PaymentForm(forms.Form):
    now = datetime.datetime.now()
    current_year = now.Year    

    MONTH_CHOICES = [(i, i) for i in range(1, 13)]
    YEAR_CHOICES = [(i, i) for i in range(current_year, current_year + 10)]
    
    credit_card_number = forms.CharField(label='Credit card number', required=False)
    cvv = forms.CharField(label='Security code(CVV)', required=False)
    expiry_month = forms.ChoiceField(label='Month', choices=MONTH_CHOICES, required=False)
    expiry_year = forms.ChoiceField(label='Year', choices=YEAR_CHOICES, required=False)
    stripe_id = forms.CharField(widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect

def view_cart(request):
    """A view that returns the cart contents page"""
    return render(request, 'cart/cart.html', {'title': 'Cart'})
    

def add_to_cart(request, id):
    """Add a product to the cart.
    If the product already exists in the cart,
    it increments its quantity by 1"""

    quantity = 1
    cart = request.session.get('cart', {})

    if not cart:
        cart[id] = cart.get(id, quantity)
    else:
        if id in cart:
            cart[id] += 1
        else:
            cart[id] = cart.get(id, quantity)

    request.session['cart'] = cart
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

def adjust_cart(request, id):
    """Decrease the quantity of a specified product.
    If there is only one product item in the cart,
    it removes the product."""

    cart = request.session.get('cart', {})
    if id in cart:
        if cart[id] > 1:
            cart[id] -= 1
        else: 
            cart.pop(id)

    request.session['cart'] = cart

    return redirect(reverse('cart:cart'))

def remove_from_cart(request, id):
    """Remove a product from the cart, regardless of its quantity."""
    cart = request.session.get('cart', {})
    quantity = request.POST.get('data-value')
    print(quantity)
    if id in cart:
        cart.pop(id)

    request.session['cart'] = cart

    return redirect(reverse('cart:cart'))

cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center mt-5 mb-3 py-2">
        {% if tickets_count > 1 %}
        <h2>Your cart ({{ tickets_count }} items)</h2>
        {% elif tickets_count == 1 %}
        <h2>Your cart ({{ tickets_count }} item)</h2>
        {% else %}
        <h2>Your cart is empty</h2>
        {% endif %}
    </div>

    <!-- Cart -->
    <div class="row mt-3">
        <article class="col-12 col-lg-10 mx-auto mt-3">
            <div class="border border-secondary rounded-lg pl-2 content-area">
                <div class="px-3 mx-auto">
                    <div class="my-3 pt-3 pb-1">
                        <h4 class="font-weight-light">Your cart summary</h4>
                    </div>
                    <!-- Cart table of contents -->
                    <table class="table table-hover table-sm">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Item</th>
                                <th scope="col" class="w-50">Feature</th>
                                <th scope="col">Votes</th>
                                <th scope="col">Unit Price</th>
                                <th scope="col"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                                <th class="align-middle" scope="row">{{ forloop.counter }}</th>
                                <td class="align-middle text-wrap"><a
                                        href="{% url 'tickets:detail' item.ticket.id %}">{{ item.ticket.title|truncatechars_html:40 }}</a>
                                </td>
                                <td class="align-middle">{{ item.quantity }}</td>
                                <td class="align-middle">£ {{ item.price|floatformat:2 }}</td>
                                <td class="align-middle">
                                    <form class="form-row" method="POST">
                                        {% csrf_token %}
                                        <div class="col-auto text-center">
                                            <a class="btn btn-sm btn-warning"
                                                href="{% url 'cart:adjust_cart' item.ticket.id %}"><i
                                                    class="fas fa-minus-square"></i></a>
                                        </div>
                                        <div class="col-auto">
                                            <a class="btn btn-sm btn-success"
                                                href="{% url 'cart:add' item.ticket.id %}"><i
                                                    class="fas fa-plus-square"></i></a>
                                        </div>
                                        <div class="col-auto">
                                            <a class="btn btn-sm btn-danger"
                                                href="{% url 'cart:remove' id=item.ticket.id %}"> <i
                                                    class="fas fa-trash-alt"></i></a>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <!-- End of cart table of contents -->

                    <!-- Car total and checkout button -->
                    <div class="mt-4 mb-3 pt-3 pb-1 d-flex justify-content-end">
                        <div class="mr-5">
                            <h5 class="font-weight-bolder mt-2">Cart Total: £ {{ total|floatformat:2 }}</h5>
                        </div>
                        {% if total > 0 %}
                        <div class="ml-4">
                            <a href="{% url 'checkout:checkout' %}" class="btn btn-success" role="button">Checkout <i
                                    class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                        </div>
                        {% else %}
                        <div class="ml-4">
                            <button class="btn btn-success" disabled>Checkout
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
                        </div>
                        {% endif %}
                    </div>
                    <!-- End of cart total -->
                </div>
            </div>
        </article>
    </div>
{% endblock %}