accounts/urls.py
from django.urls import path, reverse_lazy
from .views import signup, user_profile
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/',signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                   extra_context={'title':'Login'}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_profile, name='profile'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                success_url = reverse_lazy('accounts:password_reset_done'),
                                email_template_name='accounts/password_reset_email.html'),
         name='password_reset'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
                              template_name='accounts/password_reset_confirm.html',
                              success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

cart/urls.py
from django.urls import path, reverse_lazy
from .views import view_cart, add_to_cart, adjust_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    path('', view_cart, name='cart'),
    path('add/<id>/', add_to_cart, name='add'),
    path('adjust/<id>/', adjust_cart, name='adjust_cart'),
    path('remove/<id>/', remove_from_cart, name='remove'),
]

django_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/',TemplateView.as_view(template_name='about.html', extra_context={'title': 'About'}), name='about'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
]

tickets/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'tickets'

urlpatterns = [
    path('bugs/', views.BugListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Bugs'}), name='bugs'),
    path('features/', views.FeaturesListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Features'}), name='features'),
    path('detail/<int:pk>/', views.TicketDetailView.as_view(extra_context={'title': 'Detail'}), name='detail'),
    path('new/', views.TicketCreateView.as_view(extra_context={'title': 'New'}), name='new_ticket'),
    path('detail/<int:pk>/update', views.TicketUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/delete', views.TicketDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/comment', views.add_comment_to_ticket, name='add_comment_to_ticket'),
    path('user-bugs/<username>/', views.UserBugListView.as_view(template_name='tickets/user_tickets.html'), name='user_bugs'),
    path('user-features/<username>/', views.UserFeatureListView.as_view(template_name='tickets/user_tickets.html'), name='user_features'),
    path('vote/<int:pk>/', views.ticket_upvote, name='vote'),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        email = forms.EmailField()
        self.fields['date_joined'].widget.attrs.update({'disabled':True, 'readonly':True})
        self.fields['date_joined'].required = False

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'date_joined']
        # fields['date_joined'] = forms.CharField(widget=forms.TextInput(attrs={'disabled': True}))

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegistrationForm, UserUpdateForm
from tickets.models import Ticket


def signup(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created, please login')
            return redirect('accounts:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/signup.html', {'form': form, 'title': 'Sign up'})


@login_required
def user_profile(request):

    if request.method == 'POST':
        profile_form = UserUpdateForm(request.POST, instance=request.user)

        if profile_form.is_valid():
            # prevent a user from changing the joined date by disabling 
            # the read only tag from html
            # the form only saves username, email, first name and last name.
            form = profile_form.save(commit=False)
            form.save(update_fields=['username', 'email', 'first_name', 'last_name'])

            messages.success(request, 'Your account has been updated')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'Something went wrong, please try again')
            return redirect('accounts:profile')
    else:
        profile_form = UserUpdateForm(instance=request.user)

    context = {
        'profile_form': profile_form,
        'title': f'{request.user.username} Profile',
    }
    return render(request, 'accounts/profile.html', context)


def index(request):
    # Bugs
    total_bugs = Ticket.objects.filter(issue='Bug').count()
    total_bugs_in_progress = Ticket.objects.filter(issue='Bug', status='In Progress').count()
    total_bugs_pending = Ticket.objects.filter(issue='Bug', status='Pending').count()
    total_bugs_completed = Ticket.objects.filter(issue='Bug', status='Completed').count()
    top_voted_bugs = Ticket.objects.filter(issue='Bug').order_by('-upvotes')[:3]
    
    # Features
    total_features = Ticket.objects.filter(issue='Feature').count()
    total_features_in_progress = Ticket.objects.filter(issue='Feature', status='In Progress').count()
    total_features_pending = Ticket.objects.filter(issue='Feature', status='Pending').count()
    total_features_completed = Ticket.objects.filter(issue='Feature', status='Completed').count()
    top_voted_features = Ticket.objects.filter(issue='Feature').order_by('-upvotes')[:3]


    context = {
        'total_bugs': total_bugs,
        'total_bugs_in_progress': total_bugs_in_progress,
        'total_bugs_pending': total_bugs_pending,
        'total_bugs_completed': total_bugs_completed,
        'top_voted_bugs': top_voted_bugs,
        'total_features': total_features,
        'total_features_in_progress': total_features_in_progress,
        'total_features_pending': total_features_pending,
        'total_features_completed': total_features_completed,
        'top_voted_features': top_voted_features,
    }
    return render(request, 'accounts/index.html', context)

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block chartjs_library %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
{% endblock chartjs_library %}

{% block content %}
<p class="mt-5 pt-1">
    The AppTracker <i class="far fa-check-circle text-success"></i> is a web based app designed to easily report bugs
    and request.
</p>
<p>
    Our aim is to focus 50% of our time in solving the bugs and the other 50% of the time working of features you have
    requested.
</p>
<p>
    Please support us by voting on your most desired features. Each feature vote costs only £{{ price|floatformat:2 }}
    and you can vote as many times as you want.
</p>
<!-- Stats tables -->
<div class="row mt-3 pt-2">
    <!-- Bugs  -->
    <article class="col-12 col-md-6 mx-auto mt-3">
        <div class="border border-secondary rounded-lg pl-2 content-area">
            <div class="row justify-content-center mt-2 mt-md-0">
                <h2>Bugs</h2>
            </div>
            <div class="px-3 mx-auto">
                <table class="table table-hover table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Pending</td>
                            <td>{{ total_bugs_pending }}</td>
                        </tr>
                        <tr>
                            <td>In Progress</td>
                            <td>{{ total_bugs_in_progress }}</td>
                        </tr>
                        <tr>
                            <td>Completed</td>
                            <td>{{ total_bugs_completed }}</td>
                        </tr>
                        <tr class="table-active">
                            <td>Total</td>
                            <td>{{ total_bugs }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row justify-content-center px-3 mx-2 mt-5 mb-3">
                <h3>Top priority bugs</h3>
            </div>
            <div class="px-3 mx-auto">
                <table class="table table-hover table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Bug</th>
                            <th scope="col">Total Votes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bug in top_voted_bugs.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-wrap"><a class="text-decoration-none"
                                    href="{% url 'tickets:detail' bug.id %}">{{ bug.title|truncatechars_html:40 }}</a>
                            </td>
                            <td>{{ bug.upvotes }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row justify-content-center my-2 pt-3 pb-2">
                <a class="btn btn-outline-secondary mx-1" href="{% url 'tickets:bugs' %}">View Bugs</a>
                <a class="btn btn-outline-success mx-1" href="{% url 'tickets:new_ticket' %}">Report New Bug</a>
            </div>
        </div>
    </article>
    <!-- End of Bugs -->

    <!-- Features -->
    <article class="col-12 col-md-6 mx-auto mt-3">
        <div class="border border-secondary rounded-lg pl-2 content-area">
            <div class="row justify-content-center mt-2 mt-md-0">
                <h2>Features</h2>
            </div>
            <div class="px-3 mx-auto">
                <table class="table table-hover table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Status</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Pending</td>
                            <td>{{ total_features_pending }}</td>
                        </tr>
                        <tr>
                            <td>In Progress</td>
                            <td>{{ total_features_in_progress }}</td>
                        </tr>
                        <tr>
                            <td>Completed</td>
                            <td>{{ total_features_completed }}</td>
                        </tr>
                        <tr class="table-active">
                            <td>Total</td>
                            <td>{{ total_features }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row justify-content-center px-3 mx-2 mt-5 mb-3">
                <h3>Most popular features</h3>
            </div>
            <div class="px-3 mx-auto">
                <table class="table table-hover table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Feature</th>
                            <th scope="col">Total Votes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for feature in top_voted_features.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-wrap"><a class="text-decoration-none"
                                    href="{% url 'tickets:detail' feature.id %}">{{ feature.title|truncatechars_html:40 }}</a>
                            </td>
                            <td>{{ feature.upvotes }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row justify-content-center my-2 pt-3 pb-2">
                <a class="btn btn-outline-secondary mx-1" href="{% url 'tickets:features' %}">View Features</a>
                <a class="btn btn-outline-success mx-1" href="{% url 'tickets:new_ticket' %}">Request New Feature</a>
            </div>
        </div>
    </article>
</div>
<!-- End of features -->

<!-- Charts -->
<!-- From https://www.chartjs.org/ -->
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 mx-auto mt-3">
            <div class="row justify-content-center">
                <h4>Bugs</h4>
            </div>
            <canvas id="bugsChart" class="chart">
            </canvas>
        </div>
        <div class="col-12 col-md-6 mx-auto mt-3">
            <div class="row justify-content-center">
                <h4>Features</h4>
            </div>
            <canvas id="featuresChart" class="chart">
            </canvas>
        </div>
    </div>
</div>
<script>
    let bugs = ['{{ total_bugs_pending }}', '{{ total_bugs_in_progress }}', '{{ total_bugs_completed }}']
    let features = ['{{ total_features_pending }}', '{{ total_features_in_progress }}',
        '{{ total_features_completed }}'
    ]
</script>
<!-- End of Charts -->
{% endblock %}

{% block chartjs %}
<script src="{% static 'script/charts.js' %}"></script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Sign in</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign in</button>
            <small class="text-muted ml-2">Forgot your password? Click
                <a href="{% url 'accounts:password_reset' %}">here</a> to reset it.
            </small>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Don't have an account yet? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign up</a></small>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <div class="alert alert-info">
        <p>Your password has been reset.</p>
    </div>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary mt-4">Sign in here</a>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Reset Password</button>
        </div>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <div class="alert alert-info">
        <p>We've emailed you instructions for setting your password,
            if an account exists with the email you entered. You should receive them shortly.
        </p>
        <p>If you don't receive an email, please make sure you've entered the address you
            registered with, and check your spam folder.
        </p>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<section class="col-12 col-md-6 mx-auto mt-5 pt-3">
		<div class="row justify-content-center mb-3 pb-2">
			<h3>My profile</h3>
		</div>
		<div class="border border-secondary rounded-lg px-2 content-area">
			<form method="POST" id="user-profile" class="px-3">
				{% csrf_token %}

				{{ profile_form|crispy }}

				<div class="mt-4 mb-3 d-flex d-flex-row justify-content-center">
					<button id="submit_payment_btn" class="btn btn-outline-info">Update
					</button>
				</div>
			</form>
			<div class="px-3">
				<hr>
			</div>
			<div class="row justify-content-around my-3 py-2 px-5">
				<div>
					<a class="btn btn-outline-danger" href="{% url 'tickets:user_bugs' user.username %}">My Bugs</a>
				</div>
				<div>
					<a class="btn btn-outline-success" href="{% url 'tickets:user_features' user.username %}">My
						Features</a>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 col-md-10 col-lg-6 mx-auto mt-5 pt-2">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Sign up today!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Sign in</a></small>
    </div>
</div>

{% endblock %}