accounts/urls.py
from django.urls import path, reverse_lazy
from .views import signup, user_profile
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/',signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                   extra_context={'title':'Login'}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_profile, name='profile'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
                                template_name='accounts/password_reset.html',
                                success_url = reverse_lazy('accounts:password_reset_done'),
                                email_template_name='accounts/password_reset_email.html'),
         name='password_reset'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
                              template_name='accounts/password_reset_confirm.html',
                              success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

cart/urls.py
from django.urls import path, reverse_lazy
from .views import view_cart, add_to_cart, adjust_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    path('', view_cart, name='cart'),
    path('add/<id>/', add_to_cart, name='add'),
    path('adjust/<id>/', adjust_cart, name='adjust_cart'),
    path('remove/<id>/', remove_from_cart, name='remove'),
]

django_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/',TemplateView.as_view(template_name='about.html', extra_context={'title': 'About'}), name='about'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
]

tickets/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'tickets'

urlpatterns = [
    path('bugs/', views.BugListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Bugs'}), name='bugs'),
    path('features/', views.FeaturesListView.as_view(template_name='tickets/tickets.html', extra_context={'title': 'Features'}), name='features'),
    path('detail/<int:pk>/', views.TicketDetailView.as_view(extra_context={'title': 'Detail'}), name='detail'),
    path('new/', views.TicketCreateView.as_view(extra_context={'title': 'New'}), name='new_ticket'),
    path('detail/<int:pk>/update', views.TicketUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/delete', views.TicketDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/comment', views.add_comment_to_ticket, name='add_comment_to_ticket'),
    path('user-bugs/<username>/', views.UserBugListView.as_view(template_name='tickets/user_tickets.html'), name='user_bugs'),
    path('user-features/<username>/', views.UserFeatureListView.as_view(template_name='tickets/user_tickets.html'), name='user_features'),
    path('vote/<int:pk>/', views.ticket_upvote, name='vote'),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}

<section class="col-12 col-md-10 col-lg-8 mx-auto mt-5 pt-3">
    <div class="row justify-content-center mb-3 pb-2">
        <h3>About Me</h3>
    </div>
    <div class="border border-secondary rounded-lg px-2 content-area">
        <div class="ml-4 mt-2">
            <p class="text-monospace">Driven Full Stack Web Developer trained at Code Institute and graduated Business
                Administrator at PUC-RS, a
                leading University in Brasil.
            </p>
            <p class="text-monospace">I am now pursuing a successful career as a Web Developer.</p>
            <p class="text-monospace">I can also speak fluent Portuguese!</p>
        </div>
    </div>
</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'icon/favicon.png' %}"/>
    <!-- ### Bootstrap library ### -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block chartjs_library %} {% endblock chartjs_library %}
    {% block stripe %}{% endblock %}

    {% if title %}
        <title>AppTracker Tracker - {{ title }}</title>
    {% else %}
        <title>AppTracker Tracker</title>
    {% endif %}

</head>
<body>
    <header class="mb-2">
        <!-- NAVBAR -->
        {% include 'navbar.html' %}
        <!-- END OF NAVBAR -->
    </header>

    <main class="container">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }} mt-3"{% endif %}>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}

            {% endblock content %}
    </main>

    <footer>
        <!-- FOOTER -->
        {% include 'footer.html' %}
        <!-- END OF FOOTER -->        
    </footer>

    <!-- ### Bootstrap Scripts ### -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
    {% block chartjs %} {% endblock chartjs %}
</body>
</html>

templates/footer.html
<div class="mt-5 pt-5 pb-5 bg-haiti">
    <div class="container">
        <div class="d-flex flex-column flex-md-row">
            <div class="col-xs-12 col-lg-6">
                <p class="px-2 text-white">
                    This application was created by Giovanni Bronca.
                    <br>
                    If you would like more information about this app and it's developer, please get in touch by
                    clicking in one of the links asside.
                </p>
            </div>
            <div class="col-xs-12 col-lg-6 footer-list d-flex justify-content-around">
                <ul class="list-group list-group-horizontal">
                    <li class="text-white px-4 mx-4">
                        <a class="text-white" target="_blank" href="https://github.com/gbronca?tab=repositories">
                            <i class="fab fa-github"></i>
                        </a>
                    </li>
                    <li class="text-white px-4 mx-4">
                        <a class="text-white" target="_blank"
                            href="https://www.linkedin.com/in/giovanni-bronca-144a6828/">
                            <i class="fab fa-linkedin"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-concrete bg-haiti">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}"><span class="d-md-inline-block d-none">AppTracker</span> <i
                class="far fa-check-circle text-success"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tickets:bugs' %}">Bugs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tickets:features' %}">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-md-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tickets:new_ticket' %}">Create New Ticket</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false"><i class="far fa-user"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart' %}">
                        <i class="fas fa-shopping-cart fa-sm"></i><span> Cart</span>
                        {% if tickets_count > 0 %}
                        <span class="badge badge-success"> {{ tickets_count }}</span>
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>